In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/agriculture_dataset.csv")

In [3]:
df.head()

,High_Resolution_RGB,Multispectral_Images,Thermal_Images,Temporal_Images,Spatial_Resolution,GPS_Coordinates,Field_Boundaries,Elevation_Data,Canopy_Coverage,NDVI,...,Weed_Coverage,Pest_Damage,Crop_Growth_Stage,Expected_Yield,Crop_Type,Ground_Truth_Segmentation,Bounding_Boxes,Water_Flow,Drainage_Features,Crop_Health_Label
0,0,0,0,0,0.667324,201538,3,28.207634,8.046926,0.676945,...,1.922274,84,2,2540.784327,Wheat,1,5,41.771884,0,1
1,1,1,0,0,1.459000,215854,3,82.335147,147.512332,0.414781,...,4.851381,56,3,3227.617025,Wheat,0,1,27.564635,0,1
2,0,0,0,0,0.500442,890802,3,83.865629,30.246527,0.723610,...,5.974859,38,1,4609.938146,Maize,1,8,29.510836,0,1
3,0,0,0,0,1.865161,605584,3,20.747905,6.857820,0.405611,...,2.100598,27,2,1409.716754,Maize,0,1,34.822855,0,0
4,0,1,1,1,1.392331,871732,3,22.588815,26.168558,0.465992,...,3.025669,84,4,3905.312588,Rice,0,2,15.493255,1,0

In [4]:
core_health_prediction_df = df[["NDVI", "SAVI", "Chlorophyll_Content", "Leaf_Area_Index", "Crop_Stress_Indicator"]]

In [5]:
core_health_prediction_df.head()

,NDVI,SAVI,Chlorophyll_Content,Leaf_Area_Index,Crop_Stress_Indicator
0,0.676945,0.475536,0.829063,3.107188,79
1,0.414781,0.325712,0.435861,1.287952,88
2,0.723610,0.511144,1.001452,1.229495,59
3,0.405611,0.162857,0.962720,0.995907,11
4,0.465992,0.269888,2.111205,0.438672,79

In [13]:
pest_weed_monitoring_df = df[["Pest_Hotspots", "Weed_Coverage", "Pest_Damage", "Multispectral_Images", "Thermal_Images"]]

In [14]:
pest_weed_monitoring_df

,Pest_Hotspots,Weed_Coverage,Pest_Damage,Multispectral_Images,Thermal_Images
0,0,1.922274,84,0,0
1,0,4.851381,56,1,0
2,0,5.974859,38,0,0
3,0,2.100598,27,0,0
4,0,3.025669,84,1,1
...,...,...,...,...,...
212014,0,2.406950,5,0,0
212015,0,2.443758,38,0,0
212016,0,1.394352,37,0,0
212017,0,4.573550,2,0,0
212018,0,0.928552,30,0,0

In [16]:
environmental_stress_analysis_df = df[["Soil_Moisture", "Soil_pH", "Temperature", "Humidity", "Rainfall", "Organic_Matter", "Water_Flow"]]

In [18]:
environmental_stress_analysis_df.head()

,Soil_Moisture,Soil_pH,Temperature,Humidity,Rainfall,Organic_Matter,Water_Flow
0,31.010549,6.085810,24.627325,47.240283,7.056089,2.126335,41.771884
1,12.429003,6.776880,27.671999,44.408156,14.005230,1.751158,27.564635
2,28.454713,6.078783,23.515820,56.268020,46.152684,0.365124,29.510836
3,28.450994,6.596315,11.473797,38.637011,15.168736,2.484465,34.822855
4,8.295005,7.664008,22.502605,64.438963,9.492281,3.520753,15.493255

In [19]:
remote_sensing_UAV_analysis_df = df[["High_Resolution_RGB", "Multispectral_Images", "Thermal_Images", "Spatial_Resolution", "Bounding_Boxes", "Ground_Truth_Segmentation"]]

In [20]:
remote_sensing_UAV_analysis_df.head()

,High_Resolution_RGB,Multispectral_Images,Thermal_Images,Spatial_Resolution,Bounding_Boxes,Ground_Truth_Segmentation
0,0,0,0,0.667324,5,1
1,1,1,0,1.459000,1,0
2,0,0,0,0.500442,8,1
3,0,0,0,1.865161,1,0
4,0,1,1,1.392331,2,0

In [6]:
yield_prediction_df = df[["Expected_Yield", "Crop_Type", "Crop_Growth_Stage", "NDVI", "Canopy_Coverage", "Elevation_Data"]]

In [7]:
yield_prediction_df.head()

,Expected_Yield,Crop_Type,Crop_Growth_Stage,NDVI,Canopy_Coverage,Elevation_Data
0,2540.784327,Wheat,2,0.676945,8.046926,28.207634
1,3227.617025,Wheat,3,0.414781,147.512332,82.335147
2,4609.938146,Maize,1,0.723610,30.246527,83.865629
3,1409.716754,Maize,2,0.405611,6.857820,20.747905
4,3905.312588,Rice,4,0.465992,26.168558,22.588815